format_version: 2
environments:
  ci:
    pipelines:
      - "NullPointersAPI"
      
pipelines:
  "NullPointersAPI":
    group: team1
    materials:
      ui:
        git: "git@github.com:nullpointers-bootcamp/bootcamp-just-cinemas-api.git"
    stages:
      - buildAndTest:
          jobs:
            test:
              resources:
                - node-and-java
              tasks:
                - script: |
                    buildAndDeploy/build/build.sh team1
      - deploy:
           jobs:
            deploy:
              resources:
                - node-and-java
              tasks:
                - script: |
                    buildAndDeploy/deploy/deploy.sh team1 vivekkeypair1
